/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        'bg-dark':    '#050508',
        'bg-panel':   '#0a0a12',
        'bg-terminal':'#030308',
        'phosphor':   '#b3ffb3',
        'phosphor-dim':'#4d994d',
        'retro-red':  '#ff2020',
        'red-alert':  '#cc0000',
        'neon-cyan':  '#00f5ff',
        'neon-purple':'#bf5fff',
        'neon-green': '#39ff14',
        'amber-alert':'#ffaa00',
        'gold':       '#ffd700',
      },
      fontFamily: {
        'vt323':      ['"VT323"', 'monospace'],
        'press-start':['"Press Start 2P"', 'monospace'],
        'share-tech': ['"Share Tech Mono"', 'monospace'],
        'orbitron':   ['"Orbitron"', 'monospace'],
        'ibm-mono':   ['"IBM Plex Mono"', 'monospace'],
      },
      boxShadow: {
        'phosphor':   '0 0 8px #b3ffb3, 0 0 20px rgba(179,255,179,0.3)',
        'red':        '0 0 8px #ff2020, 0 0 20px rgba(255,32,32,0.4)',
        'cyan':       '0 0 8px #00f5ff, 0 0 20px rgba(0,245,255,0.3)',
        'purple':     '0 0 8px #bf5fff, 0 0 20px rgba(191,95,255,0.3)',
        'amber':      '0 0 8px #ffaa00, 0 0 20px rgba(255,170,0,0.3)',
        'green':      '0 0 8px #39ff14, 0 0 20px rgba(57,255,20,0.3)',
        'inset-crt':  'inset 0 0 120px rgba(0,0,0,0.8)',
        'panel':      '0 0 0 1px rgba(179,255,179,0.12), 0 4px 24px rgba(0,0,0,0.8)',
      },
      animation: {
        'marquee':      'marquee 22s linear infinite',
        'flicker':      'flicker .14s step-start infinite',
        'crt-flicker':  'crt-flicker 8s step-start infinite',
        'scanline-move':'scanline-move 6s linear infinite',
        'blink-hard':   'blink-hard 1s step-start infinite',
        'glow-pulse':   'glow-pulse 2.5s ease-in-out infinite',
        'static-noise': 'static-noise .4s steps(3) infinite',
        'type-cursor':  'type-cursor 1s step-start infinite',
        'spin-slow':    'spin 12s linear infinite',
        'float-up':     'float-up 8s ease-in-out infinite',
      },
      keyframes: {
        marquee:        { from:{transform:'translateX(0)'}, to:{transform:'translateX(-50%)'} },
        flicker:        { '0%,100%':{opacity:1},'49%':{opacity:.96},'51%':{opacity:.93},'55%':{opacity:.98} },
        'crt-flicker':  { '0%,95%,97%,100%':{opacity:1},'96%':{opacity:.7},'98%':{opacity:.85} },
        'scanline-move':{ from:{transform:'translateY(-100vh)'}, to:{transform:'translateY(100vh)'} },
        'blink-hard':   { '0%,49%':{opacity:1},'50%,100%':{opacity:0} },
        'glow-pulse':   { '0%,100%':{textShadow:'0 0 6px currentColor'}, '50%':{textShadow:'0 0 20px currentColor, 0 0 40px currentColor'} },
        'static-noise': { '0%':{transform:'translate(0,0)'},'33%':{transform:'translate(-2%,-1%)'},'66%':{transform:'translate(1%,2%)'},'100%':{transform:'translate(-1%,1%)'} },
        'type-cursor':  { '0%,49%':{borderRightColor:'currentColor'},'50%,100%':{borderRightColor:'transparent'} },
        'float-up':     { '0%,100%':{transform:'translateY(0)',opacity:.6},'50%':{transform:'translateY(-24px)',opacity:1} },
      },
    },
  },
  plugins: [],
};
